### ISSUE TITLE
Are the gene annotation files of your article available?

### ISSUE THREAD

**Issue by shangshanzhizhe** [lloydlow/BrahmanAngusAssemblyScripts#5]
Hi, 

Sorry for opened a new issue here. I'd like to know that are the chromosome sequences and gene annotation files of your article available? if yes, can you send me a copy of that please? 
You can also contact me by shangzhezhang@gmail.com.
Thanks a lot!

Best,
Shangzhe

**Comment by lloydlow** [comment]
Dear Shangzhe,

You can get a copy of the annotation from Ensembl.
https://asia.ensembl.org/Bos_taurus_hybrid/Info/Index 

Angus assembly: https://www.ncbi.nlm.nih.gov/assembly/GCA_003369685.2/

Brahman assembly: https://www.ncbi.nlm.nih.gov/assembly/GCF_003369695.1/ 

Please let me know if you have any issue getting the annotation.

Regards,
Lloyd
